version: '3.8'

services:
  java-app:
    build: .
    container_name: java_container
    volumes:
      - ./src:/app/src  # Mapeia o diretório 'src' local para '/app/src' no container
    working_dir: /app  # Define o diretório de trabalho no container
    ports:
      - "8080:8080"  # (Opcional) Se sua aplicação rodar em uma porta
    command: bash -c "javac -d out src/main/Main.java src/agenda/Agenda.java && java -cp out main.Main"